version: "3.7"

services:
  main:
    image: prettyrollcake/nostr-rs-relay:v0.7.16@sha256:603dfd018dcd70092253ca24e026d9b08689d54b8f35c05a738715ff2264ac9a
    restart: on-failure
    ports:
      - "${APP_NOSTR_RS_RELAY_PORT}:8080"
    volumes:
      - ${APP_DATA_DIR}/data/db:/usr/src/app/db
      - ${APP_DATA_DIR}/data/config.toml:/usr/src/app/config.toml
    networks:
      default:
        ipv4_address: $APP_NOSTR_RS_RELAY_IP

